# Permalinks
permalink:        /:title
relative_permalinks: true

# Setup
title:            Chris Hagan
tagline:          Commit Year
url:              http://chagan.github.io
paginate:         1
baseurl:          /
author:
  name:           Chris Hagan
  url:            https://twitter.com/chrishagan
  email:          chrishagan23@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/chagan/chagan.github.io
